### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by coolcoolcoolcool123** [SuperheroesX-Dev/SuperheroesX#12]
![bug](https://user-images.githubusercontent.com/49095157/55275845-23e8ef00-52e4-11e9-9d69-e3b1e216e413.PNG)

**Comment by TheDoctorOne** [comment]
`[modloading-worker-7/ERROR]: Failed to create mod instance. ModID: sx, class com.sx_dev.sx.SuperheroesX
java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeConfigSpec$Builder.defineEnum(Ljava/lang/String;Ljava/lang/Enum;[Ljava/lang/Enum;)Lnet/minecraftforge/common/ForgeConfigSpec$ConfigValue;
	at com.sx_dev.sx.util.config.ModConfig$ClientConfig$HUDConfig.init(ModConfig.java:66) ~[?:1.13.2-0.4.1]
	at com.sx_dev.sx.util.config.ModConfig$ClientConfig.init(ModConfig.java:114) ~[?:1.13.2-0.4.1]
	at com.sx_dev.sx.util.config.ModConfig.<clinit>(ModConfig.java:26) ~[?:1.13.2-0.4.1]
	at com.sx_dev.sx.SuperheroesX.<init>(SuperheroesX.java:43) ~[?:1.13.2-0.4.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:130) [?:25.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$1318/302241671.accept(Unknown Source) [?:25.0]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$1317/352318951.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$1317/352318951.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:111) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$9(ModList.java:120) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$1471/779556431.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]`
My latest.log here. Same error i believe.

**Comment by Sh0wYaH0wda** [comment]
ive got the same crash i believe ![image](https://user-images.githubusercontent.com/40673661/59984700-822f2080-95fa-11e9-8705-363d90281bae.png)

[latest.log](https://github.com/SuperheroesX-Dev/SuperheroesX/files/3318812/latest.log)

**Comment by Minecraftschurli** [comment]
Just deleting the config file should work

**Comment by Sh0wYaH0wda** [comment]
what if there isnt a config file for superherpsx? or which config file are you talking about
